// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelBD.Infrastructure.Persistence;

#nullable disable

namespace TravelBD.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TravelDbContext))]
    partial class TravelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelBD.Domain.Entities.Accommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ApproxPriceRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BookingUrl")
                        .HasColumnType("text");

                    b.Property<int>("BudgetLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("HighlightFeature")
                        .HasColumnType("text");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Accommodations");
                });

            modelBuilder.Entity("TravelBD.Domain.Entities.Attraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BanglaName")
                        .HasColumnType("text");

                    b.Property<string>("BestTimeToVisit")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("EntryFeeBdt")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("TravelBD.Domain.Entities.DestinationAdvisory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("DestinationAdvisories");
                });

            modelBuilder.Entity("TravelBD.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BanglaName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsMajorHub")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTouristDestination")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TravelBD.Domain.Entities.RouteSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvgDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId", "DestinationId")
                        .IsUnique();

                    b.ToTable("RouteSegments");
                });

            modelBuilder.Entity("TravelBD.Domain.Entities.TransportOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArrivalStation")
                        .HasColumnType("text");

                    b.Property<string>("BookingLinksJson")
                        .HasColumnType("text");

                    b.Property<string>("DepartureStation")
                        .HasColumnType("text");

                    b.Property<int>("FrequencyPerDay")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxCostBdt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinCostBdt")
                        .HasColumnType("numeric");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RouteSegmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScheduleNotes")
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteSegmentId");

                    b.ToTable("TransportOptions");
                });

            modelBuilder.Entity("TravelBD.Domain.Entities.Accommodation", b =>
                {
                    b.HasOne("TravelBD.Domain.Entities.Location", "Location")
                        .WithMany("Accommodations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TravelBD.Domain.Entities.Attraction", b =>
                {
                    b.HasOne("TravelBD.Domain.Entities.Location", "Location")
                        .WithMany("Attractions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TravelBD.Domain.Entities.DestinationAdvisory", b =>
                {
                    b.HasOne("TravelBD.Domain.Entities.Location", "Location")
                        .WithMany("Advisories")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TravelBD.Domain.Entities.RouteSegment", b =>
                {
                    b.HasOne("TravelBD.Domain.Entities.Location", "Destination")
                        .WithMany("IncomingRoutes")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelBD.Domain.Entities.Location", "Origin")
                        .WithMany("OutgoingRoutes")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("TravelBD.Domain.Entities.TransportOption", b =>
                {
                    b.HasOne("TravelBD.Domain.Entities.RouteSegment", "RouteSegment")
                        .WithMany("TransportOptions")
                        .HasForeignKey("RouteSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteSegment");
                });

            modelBuilder.Entity("TravelBD.Domain.Entities.Location", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Advisories");

                    b.Navigation("Attractions");

                    b.Navigation("IncomingRoutes");

                    b.Navigation("OutgoingRoutes");
                });

            modelBuilder.Entity("TravelBD.Domain.Entities.RouteSegment", b =>
                {
                    b.Navigation("TransportOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
